version: '2.0'

services:
  adsbhub:
    image: ${AH_CONTAINER}
    tty: true
    container_name: adsbhub
    restart: always
    environment:
      - TZ=${FEEDER_TZ}
      - SBSHOST=ultrafeeder
      - CLIENTKEY=${FEEDER_ADSBHUB_STATION_KEY}
