services:
  adsbhub_STAGE2NUM:
    image: ${AH_CONTAINER}
    tty: true
    container_name: adsbhub_STAGE2NUM
    restart: always
    environment:
      - TZ=${FEEDER_TZ_STAGE2NUM}
      - SBSHOST=ultrafeeder_STAGE2NUM
      - CLIENTKEY=${FEEDER_ADSBHUB_STATION_KEY_STAGE2NUM}
      - S6_KILL_GRACETIME=1000
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    tmpfs:
      - /run:exec,size=64M
      - /var/log
