services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    healthcheck:
      disable: true
    restart: always
    environment:
      - DOZZLE_NO_ANALYTICS=1
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${AF_DAZZLE_PORT:-9999}:8080

  adsb-setup-proxy:
    container_name: adsb-setup-proxy
    image: alpine
    healthcheck:
      disable: true
    stop_signal: SIGKILL
    command: /usr/bin/journalctl --unit=adsb-setup.service --unit=adsb-docker.service --unit=adsb-log.service --follow
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - /run/log/journal:/run/log/journal
