version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always
    environment:
      - DOZZLE_NO_ANALYTICS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${_ADSBIM_STATE_DAZZLE_PORT:-9999}:8080

  adsb-setup-proxy:
    container_name: adsb-setup-proxy
    image: alpine
    command: tail -n500 -f /opt/adsb-setup.log
    volumes:
      - /opt/adsb/adsb-setup.log:/opt/adsb-setup.log
