version: '2.0'

services:
  piaware:
    image: ${FA_CONTAINER}
    tty: true
    container_name: piaware
    restart: always
    ports:
      - 8081:8080
      - 8082:80
    environment:
      - BEASTHOST=ultrafeeder
      - LAT=${FEEDER_LAT}
      - LONG=${FEEDER_LONG}
      - TZ=${FEEDER_TZ}
      - FEEDER_ID=${FEEDER_PIAWARE_FEEDER_ID}
    tmpfs:
      - /run:exec,size=64M
      - /var/log
