version: '2.0'

services:
  fr24feed:
    image: ${FR24_CONTAINER}
    tty: true
    container_name: fr24feed
    restart: always
    ports:
      - ${_ADSBIM_STATE_FLIGHTRADAR_PORT:-8754}:8754
    environment:
      - BEASTHOST=ultrafeeder
      - FR24KEY=${FEEDER_FR24_SHARING_KEY}
      - FR24KEY_UAT=${FEEDER_FR24_UAT_SHARING_KEY}
      - MLAT=${FEEDER_FR24_MLAT}
    tmpfs:
      - /run:exec,size=64M
      - /var/log
