services:
  planewatch_STAGE2NUM:
    image: ${PW_CONTAINER}
    healthcheck:
      disable: true
    tty: true
    container_name: planewatch_STAGE2NUM
    restart: always
    cpu_period: 50000
    cpu_quota: 7500
    environment:
      - BEASTHOST=ultrafeeder_STAGE2NUM
      - LAT=${FEEDER_LAT_STAGE2NUM}
      - LONG=${FEEDER_LONG_STAGE2NUM}
      - ALT=${FEEDER_ALT_M_STAGE2NUM}m
      - TZ=${FEEDER_TZ_STAGE2NUM}
      - API_KEY=${FEEDER_PLANEWATCH_API_KEY_STAGE2NUM}
      - S6_KILL_GRACETIME=1000
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    tmpfs:
      - /run:exec,size=64M
      - /var/log
