version: '2.0'

services:
  rbfeeder:
    image: ${RB_CONTAINER}
    tty: true
    container_name: rbfeeder
    restart: always
    environment:
      - BEASTHOST=ultrafeeder
      - UAT_RECEIVER_HOST=${FEEDER_UAT978_HOST}
      - LAT=${FEEDER_LAT}
      - LONG=${FEEDER_LONG}
      - ALT=${FEEDER_ALT_M}
      - TZ=${FEEDER_TZ}
      - SHARING_KEY=${FEEDER_RADARBOX_SHARING_KEY}
    tmpfs:
      - /run:exec,size=64M
      - /var/log
    volumes:
      - /opt/adsb/rb/thermal_zone0:${FEEDER_RB_THERMAL_HACK:-/tmp/rbt}
      - /opt/adsb/rb/cpuinfo:${FEEDER_RB_CPUINFO_HACK:-/tmp/rbc}:ro
