services:
  webproxy:
    image: ghcr.io/sdr-enthusiasts/webproxy
    tty: true
    container_name: webproxy
    hostname: webproxy
    restart: always
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - AUTOGENERATE=ON
      - VERBOSELOG=ON
      - GEOIP_DEFAULT=ALLOW
      - REVPROXY=
                  map|http://host.docker.internal:8080,
                  tar1090|http://host.docker.internal:8080,
                  stats|http://host.docker.internal:8080/graphs1090/,
                  graphs|http://host.docker.internal:8080/graphs1090/,
                  graphs1090|http://host.docker.internal:8080/graphs1090/,
                  piaware|http://host.docker.internal:8088,
                  pa|http://host.docker.internal:8088,
                  flightaware|http://host.docker.internal:8088,
                  piaware-stats|http://host.docker.internal:8082,
                  fa-stats|http://host.docker.internal:8082,
                  fa-status|http://host.docker.internal:8082,
                  setup|http://host.docker.internal:5000,
                  config|http://host.docker.internal:5000
      - REDIRECT=
                  fr|http://host.docker.internal:8754,
                  fr24|http://host.docker.internal:8754,
                  flightradar|http://host.docker.internal:8754,
                  flightradar24|http://host.docker.internal:8754,
                  fr-status|http://host.docker.internal:8754,
                  portainer|https://host.docker.internal:9443,
                  ptnr|https://host.docker.internal:9443,
      - SSL=DISABLED
      - VERBOSELOG=on
      - IPV6=ON
    cap_add:
        - NET_ADMIN
    tmpfs:
        - /tmp:rw,nosuid,nodev,noexec,relatime,size=128M
        - /var/log/nginx:rw,nosuid,nodev,noexec,relatime,size=128M
    volumes:
        - /opt/adsb/webproxy:/run/nginx
        - "/etc/localtime:/etc/localtime:ro"
        - "/etc/timezone:/etc/timezone:ro"
