services:
  zerotier:
    image: zerotier/zerotier:latest
    container_name: zerotier
    devices:
      - /dev/net/tun
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    environment:
      - net=host
    volumes:
      - /var/lib/zerotier-one:/var/lib/zerotier-one
